### ISSUE TITLE
ESLint couldn't find the plugin "eslint-plugin-rxjs".

### ISSUE THREAD

**Issue by alogim** [timdeschryver/eslint-plugin-ngrx#170]
If I run `eslint -c .eslintrc.json . --ext .json,.html,.ts,.md` in my project, I get the following output:
```
Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the plugin "eslint-plugin-rxjs".

(The package "eslint-plugin-rxjs" was not found when loaded as a Node module from the directory "/path/to/my/project/navbar-test".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-rxjs@latest --save-dev

The plugin "eslint-plugin-rxjs" was referenced from the config file in "--config#overrides[6] » plugin:ngrx/recommended".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

My .eslintrc.json contains the following section and others which do not use the ngrx plugin:
```
// See https://github.com/timdeschryver/eslint-plugin-ngrx#manual
{
  "files": [
    "*.ts"
  ],
  "extends": [
    "plugin:ngrx/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2019,
    "project": "./tsconfig.json",
    "sourceType": "module"
  },
  "plugins": [
    "ngrx"
  ]
},
```
I have `"eslint-plugin-ngrx": "^1.28.0"` in my package.json. Do I also need `eslint-plugin-rxjs` in my package.json? It is not mentioned in the documentation though.
Can anyone help?

**Comment by alogim** [comment]
Never mind, deleting the node_modules folder and running npm install again fixed the problem.

**Comment by alogim** [comment]
If I comment the above section in my .eslintrc.json everything works fine. So it seems that package is needed?

**Comment by timdeschryver** [comment]
@alogim you need to that dependency, but I thought it would be installed automatically 🤔

**Comment by timdeschryver** [comment]
@alogim have you tried removing the `node_modules` and to run `npm install` again?

**Comment by sikmowe** [comment]
I tried the @PhilFlash workaround but I still got this:
```
[error] TypeError: Failed to load plugin 'ngrx' declared in '.eslintrc.json#overrides[0]': Class extends value undefined is not a constructor or null
Referenced from: \.eslintrc.json
    at Object.<anonymous> (\node_modules\eslint-plugin-ngrx\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js:12:34)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
...
```
package.json
```
"dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/cdk": "^13.0.1",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/material": "^13.0.1",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "@ngrx/effects": "^13.0.1",
    "@ngrx/entity": "^13.0.1",
    "@ngrx/store": "^13.0.1",
    "@ngrx/store-devtools": "^13.0.1",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.2",
    "@angular-eslint/builder": "13.0.0-alpha.0",
    "@angular-eslint/eslint-plugin": "13.0.0-alpha.0",
    "@angular-eslint/eslint-plugin-template": "13.0.0-alpha.0",
    "@angular-eslint/schematics": "13.0.0-alpha.0",
    "@angular-eslint/template-parser": "13.0.0-alpha.0",
    "@angular/cli": "~13.0.2",
    "@angular/compiler-cli": "~13.0.0",
    "@ngrx/schematics": "^13.0.1",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "5.3.0",
    "@typescript-eslint/parser": "5.3.0",
    "eslint": "^8.2.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^16.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.2",
    "eslint-plugin-ngrx": "^1.46.4",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-rxjs": "^4.0.3",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "prettier": "^2.4.1",
    "typescript": "~4.4.3"
  }
```
any thoughts?

**Comment by timdeschryver** [comment]
@sikmowe have you tried using angular eslint v12?
I suppose we need to upgrade to v13 to make it compatible.

**Comment by sikmowe** [comment]
@timdeschryver thanks for the heads-up! After
`ng add @angular-eslint/schematics@12.7.0`
It worked despite some warnings. I'll keep my eyes here for any updates.

**Comment by timdeschryver** [comment]
@sikmowe feel free to try out v2-beta.1, which is just released.

**Comment by sikmowe** [comment]
Cool, @timdeschryver, no errors using 2.0.0-beta.2. Thank you.

**Comment by timdeschryver** [comment]
The v2 is released 🎉
If there are some problems, feel free to open a new issue.
Thanks!
