### ISSUE TITLE
Bug on-function-explicit-return-type

### ISSUE THREAD

**Issue by bryantlikes** [timdeschryver/eslint-plugin-ngrx#273]
## Behavior

[error] TypeError: Cannot read property 'range' of undefined
Occurred while linting [path removed]wizard.reducer.ts:56
Rule: "ngrx/on-function-explicit-return-type"
    at SourceCode.getTokenBefore (C:\code\my-app\node_modules\eslint\lib\source-code\token-store\index.js:298:18)
    at getFixes (C:\code\my-app\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:52:38)
    at Object.fix (C:\code\my-app\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:41:45)
    at normalizeFixes (C:\code\my-app\node_modules\eslint\lib\linter\report-translator.js:193:28)
    at C:\code\my-app\node_modules\eslint\lib\linter\report-translator.js:223:22
    at Array.map (<anonymous>)
    at mapSuggestions (C:\code\my-app\node_modules\eslint\lib\linter\report-translator.js:217:10)
    at C:\code\my-app\node_modules\eslint\lib\linter\report-translator.js:365:55
    at Object.report (C:\code\my-app\node_modules\eslint\lib\linter\linter.js:1047:41)
    at CallExpression[callee.name='createReducer'] CallExpression[callee.name='on'] > ArrowFunctionExpression:not([returnType.typeAnnotation], :has(CallExpression)) (C:\code\my-app\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:35:25)

Rule is failing with an exception

## Code snippet

export const reducer = createReducer(
  initialState,
 // this causes the exception
  on(fromActions.reset, () => initialState)
)

## I would be willing to submit a PR to fix this issue :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by bryantlikes** [comment]
Create PR #274
